---

# Integration testing playbook
# ----------------------------

# A playbook for testing and integration.

# It will provision the `test` hosts in the inventory,
# which will, by default, specify the provided vagrant VM.

# This playbook should aim to test the most extensive
# or comprehensive configuration possible for your role.


- name: 'Nginx role integration tests'

  hosts: test

  vars:
    # custom_configuration: value

  pre_tasks:
    # Most vagrant boxes have outdated repositories
    - name: APT update
      sudo: yes
      apt: update_cache=yes

  post_tasks:
    # Produce a default site pointing to the shared folder
    - include: tasks/site.yml
      site: www
      port: 80
      block_robots: true
      server_name: 192.168.33.20
      access_log: /var/www/site/~access.log
      error_log: /var/www/site/~error.log
      document_root: /var/www/site

  roles:
    - '.'    # The current directory itself is the role

