---

- name: Create sites directories
  sudo: yes
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - "{{nginx_available_sites_dir}}"
    - "{{nginx_enabled_sites_dir}}"
  notify: restart nginx
  tags:
    - nginx
    - frontend
    - conf

- name: Configure Nginx
  sudo: yes
  template:
    src: "{{item}}"
    dest: "{{nginx_conf_dir}}/{{item}}"
  with_items:
    - nginx.conf
    - fastcgi_params
    - uwsgi_params
  notify: restart nginx
  tags:
    - nginx
    - frontend
    - conf

- name: Configure Nginx
  sudo: yes
  copy:
    src: "{{item}}"
    dest: "{{nginx_conf_dir}}/{{item}}"
  with_items:
    - mime.types
  notify: restart nginx
  tags:
    - nginx
    - frontend
    - conf

- include: site.yml
  vars:
    site: "{{nginx_default_site_name}}"
    template: default-site
    when: nginx_create_default_site

- include: site.yml
  vars:
    site: status
    template: status-site
    when: nginx_create_status_site
